export const FETCHING_MOVIES = 'FETCHING_MOVIES';
export const FETCH_MOVIES = 'FETCH_MOVIES';

export const FETCH_MOVIE = 'FETCH_MOVIE';

export const RECEIVED_MOVIES = 'RECEIVED_MOVIES';

export const SEARCHING_MOVIES = 'SEARCHING_MOVIES';
export const FIND_MOVIE = 'FIND_MOVIE';
export const DONE_SEARCHING = 'DONE_SEARCHING';
export const CLOSED_SEARCH_MODAL = 'CLOSED_SEARCH_MODAL';

export const SHOW_TOAST = 'SHOW_TOAST';
export const HIDE_TOAST = 'HIDE_TOAST';

export const ADD_MOVIE = 'ADD_MOVIE';
export const DELETE_MOVIE = 'DELETE_MOVIE';
